apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "testiculate.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
