apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: testiculate
  name: testiculate-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testiculate-role
subjects:
- kind: ServiceAccount
  name: testiculate
  namespace: cpe
