apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: testiculate
rules:
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["get", "describe", "list", "create"]
- apiGroups: ["*"]
  resources: ["rolebindings"]
  verbs: ["get", "list", "create"]
